#!/bin/sh -e

case $# in
0)
    args="$@"
    ;;

*)
    case "$1" in
    "-h"|"--help")
	echo "Usage: $0 [-h|--help]"
	echo "       $0 [-v|--viewers 'viewer-list'] [arguments]"
	echo "NOTE: (viewer-list must be quoted to separate it from arguments)"
	echo ""
	echo "Example:"
	echo "  $0 -v 'konqueror ephipany lynx' http://www.google.com"
	exit 0
	;;
    
    "-v"|"--viewers")
	viewers="$2"
	shift
	;;
    
    *)
	;;
    
    esac
esac

# If no viewer list given on the command line, check the env
if [ -z "$viewers" ]; then
    if [ -n "$DOCVIEWERS" ]; then
	viewers="$DOCVIEWERS"
    else
	# The order of the viewers here is an attempt to rank them in order
	# of most likely to be an add-on.  The idea is to use the viewer that
	# a user chose to install over those included with the base system.
	viewers="qpdfview atril epdfview okular evince Preview mupdf"
	if [ `uname` == 'Darwin' ]; then
	    # Mac OS X has an 'open' command that runs the default app
	    # for a given argument.
	    viewers="open $viewers"
	fi
    fi
fi

# Find a viewer from the list
for v in $viewers; do
    if which $v > /dev/null 2>&1; then
	viewer=$v
	break
    fi
done

if [ -z "$viewer" ]; then
    # Didn't find anything...
    echo "None of the following viewers were found on this system:"
    echo ""
    echo ${viewers}
    echo ""
    echo "Make sure at least on of these viewers is installed and your PATH is"
    echo "properly configured."
    exit 1
fi

for document in "$@"; do
    $viewer $document
done
